version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:latest
      #ubuntu-2004:202010-01
    steps:
      - checkout
      #- run:
          #name: Installing AWS CLI
          #command: |
            #sudo apt-get update
            #sudo apt install python3-pip
            #sudo pip3 install awsebcli --upgrade
      - run: 
            npm install && npm run build
      #- run: aws s3 sync ./build s3://myfirsts3maggi
      # - persist_to_workspace:
      #      root: .
      #      paths:
            # - .
  # test:
  #   machine:
  #     image: ubuntu-2004:202010-01
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - checkout
  #     - run: cd ./app && npm run test
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .
  # deploy:
  #   machine:
  #       image: ubuntu-2004:202010-01
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - checkout
  #     - run: aws s3 sync ./app/build s3://myfirsts3maggi
    

workflows:
  build_test_deploy:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      # - deploy:
      #     requires:
      #       - test