version: 2.1

jobs:
  build:
    machine:
      image: ubuntu/default

    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: 
            npm install && npm run build
      - run: aws s3 sync ./build s3://myfirsts3maggi

workflows:
  build_test_deploy:
    jobs:
      - build